feat: logout redirection
TOSIT-IO/tdp-ui pull request #110
Opened 2022-12-26 15:19 UTC by mdrutel

#### Which issue(s) this PR fixes

Fixes #60 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-12-27 11:55 UTC, PaulFarault approved these changes

2022-12-27 13:26 UTC, PaulFarault approved these changes

2022-12-29 09:46 UTC, gboutry approved these changes

2023-01-02 09:32 UTC, PaulFarault requested changes
@mdrutel your PR is good but it does not solve the initial issue (#60).

You should add least add a `Link` to go back to `/` on the disconnected/error page before merging.

2023-01-05 10:06 UTC, PaulFarault approved these changes

2023-01-05 10:06 UTC, merged