feat: create missing toasts
TOSIT-IO/tdp-ui pull request #159
Opened 2023-02-01 12:58 UTC by mdrutel

#### Which issue(s) this PR fixes

Fixes #150 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-02-02 10:20 UTC, PaulFarault commented
Seems good.

Though, response objects are difficult to manipulate because tdp-server doesn't provide any schema for the return type of deploy endpoints. Thus, the OpenAPI Generator assigns an `any` type to the res object.

It may be worth fixing this issue (https://github.com/TOSIT-IO/tdp-server/issues/105) and updating the schema to benefit from Typescript for this PR.

2023-02-06 16:48 UTC, PaulFarault requested changes
@mdrutel well done for https://github.com/TOSIT-IO/tdp-server/issues/105

If you generate the client using the new schema, you'll see that we don't need to parse the response to JSON.

2023-03-06 13:13 UTC, PaulFarault requested changes

2023-03-06 13:13 UTC, PaulFarault commented on src/components/Services/VariablesDisplay/ValidateBar.tsx
> +    toast.info('Validating configuration...')
Is this toast is useful as the operation is almost instant?

2023-03-06 13:13 UTC, PaulFarault commented on src/pages/deploy/new/reconfigure.tsx
> +          onClick={() => toast.info('Reconfiguring...') && reconfigureDeploy()}
Ideally, we should have a toast similar to the one for DAG and operations deployments. This one may not be useful without any id returned by the server.

2023-03-08 10:32 UTC, mdrutel commented
I took into account all the comments above, after doing a rebase.

2023-03-08 10:45 UTC, PaulFarault requested changes

2023-03-08 10:45 UTC, PaulFarault commented on src/pages/deploy/new/reconfigure.tsx
> +    const res = reconfigureDeploy()
You forgot to remove this line:
```suggestion
```

2023-03-08 10:45 UTC, PaulFarault commented on src/pages/deploy/new/reconfigure.tsx
> +      console.log(res)
This one too:

```suggestion
```

2023-03-08 10:45 UTC, PaulFarault commented on src/pages/deploy/new/reconfigure.tsx
> +      error.status === undefined && toast.error(String(error))
Won't it be better to use an `if`/`else` block here?

2023-03-08 13:13 UTC, PaulFarault approved these changes

2023-03-15 15:06 UTC, pvalentin01 approved these changes
Great,
Perhaps add missing toasts when you choose deployment from dag "from sources" or "to targets" and there's no operation to deploy
And also to reconfigure cluster if there's nothing to "deploy reconfigure"

2023-03-17 10:38 UTC, PaulFarault commented
> Perhaps add missing toasts when you choose deployment from dag "from sources" or "to targets" and there's no operation to deploy

I'll open a new issue

2023-04-03 11:48 UTC, merged