feat: 123-past-deployment-text-logs
TOSIT-IO/tdp-ui pull request #183
Opened 2023-02-27 12:35 UTC by jpsavy

#### Which issue(s) this PR fixes

Fixes #123 

#### Additional comments

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-03-08 11:22 UTC, PaulFarault requested changes
Feature is ok, code still miss one refactor to be perfect.

2023-03-08 11:22 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +
This state doesn't seem to be used.

```suggestion
```

2023-03-08 11:22 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +      <div>
There is no need for those wrapper as there is already only 1 parent `div` for the component.

2023-03-08 11:22 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +
`logviewtext` doesn't seem to be used either:

```suggestion
```

2023-03-08 11:22 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +          </button>
This could be in it's own component.

2023-03-08 11:22 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +      </pre>
This could be in it's own component too.

IMO, the hook the `useDeploymentOperation` hook should be called inside this new component.

2023-03-08 18:23 UTC, pvalentin01 approved these changes
Great !

2023-03-09 12:15 UTC, jpsavy commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +      </pre>
This code is now in the **DetailLogView** component.

2023-03-09 12:15 UTC, jpsavy commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +          </button>
This code is now in the **LogViewButton** component.

2023-03-09 12:16 UTC, jpsavy commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +
Unused code deleted.

2023-03-09 12:18 UTC, jpsavy commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +      <div>
Those wrappers are now removed.

2023-03-09 12:18 UTC, jpsavy commented on src/components/Deploy/DeployLogs/OperationsList.tsx
> +
This unused state is now removed.

2023-03-09 14:26 UTC, PaulFarault approved these changes

2023-03-09 14:32 UTC, merged