feat: 129-logs-pagination first version
TOSIT-IO/tdp-ui pull request #185
Opened 2023-02-27 18:14 UTC by jpsavy

#### Which issue(s) this PR fixes

Fixes #129 

#### Additional comments

Pagination of the deployment list

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-03-03 10:55 UTC, PaulFarault reviewed
Nice first version!

You should start by:

- remove commented code snippet (those are not useful)
- rebase on master to resolve current conflicts

2023-03-03 10:55 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogs.tsx
> +        </div>
I'm not sure that it's necessary!

2023-03-03 10:55 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogs.tsx
> +                    {deployTab.map((d) => (
You should refactor it in it's own component

2023-03-03 10:55 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +  const [currentPage, setCurrentPage] = useState(1)
`limit` and `currentPage` doesn't seem to be used.

2023-03-03 10:55 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +                    {currentDeployLogsPage.map((d) => (
This could be in it's own component

2023-03-03 10:55 UTC, PaulFarault reviewed
Nice first version!

You should also:

- remove commented code snippet (those are not useful)
- rebase on master to resolve current conflicts

2023-03-06 16:21 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogs.tsx
> +        </div>
Done

2023-03-06 16:22 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogs.tsx
> +        </div>
Done

2023-03-06 16:22 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogs.tsx
> +                    {deployTab.map((d) => (
Done

2023-03-06 16:22 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +  const [currentPage, setCurrentPage] = useState(1)
Done

2023-03-06 16:22 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +                    {currentDeployLogsPage.map((d) => (
Done

2023-03-08 17:52 UTC, pvalentin01 requested changes
Great first version, some improvment could be done :

1. Write the text of the navigation bar in english : previous page, current page, next page
2. The current page starts at 0, it should be 1
3. The font-size of the text for the current page may be the same as the previous and next buttons
4. A little problem with the last page to show if there's more than 2 logs pages.
The test for the next page : `currentDeployLogsPage.length >= offset + limit + 1` should be replaced with `currentDeployLogsPage.length >= offset + 1`
5. The button previous and next should be shown only if there's a page to show
this will simplify the code with only a test to show the previous and next button and delete test
    - For the  previous button you could write :
       `` { Math.floor(offset / limit) > 0 &&
          <button
            type='button'
            onClick={() => setOffset(offset - limit)}``
    - For the  next button  :
       ``{currentDeployLogsPage.length >= offset + 1 &&
          <button
            type="button"
            onClick={() => setOffset(offset + limit)}``

2023-03-08 17:52 UTC, pvalentin01 commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +                : 'vrai'
unnecessary code, no effect

2023-03-20 09:40 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +      <div className="px-4 sm:px-6 lg:px-8">
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +        <div className="mt-auto mb-3 flex items-center justify-center space-x-1 p-5 text-gray-700">
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +              'bg-gray-200 text-gray-700',
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +              'flex items-center gap-1 px-2 py-[0.15rem] text-sm hover:bg-gray-200'
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +          <p>Page courante : {Math.floor(offset / limit)}</p>
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +              'flex items-center gap-1 px-2 py-[0.15rem] text-sm hover:bg-gray-200'
Done

2023-03-20 09:41 UTC, jpsavy commented on src/hooks/usePastDeploymentsList.ts
> +      // const res = await getDeployments(15,18)
Done

2023-03-20 09:41 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +                : 'vrai'
Done

2023-04-03 08:47 UTC, PaulFarault reviewed
Good job! You may want to refactor/rename some files are their name may be confusing when trying to differentiate them.

2023-04-03 08:47 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +                    })
You can replace the anonymmous function by an arrow funciton to simplify your code here.

2023-04-03 08:47 UTC, PaulFarault commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +      </div>
It would be easier to read if you move this in its own component (you can define it on the same page).

2023-04-03 08:47 UTC, PaulFarault commented on src/hooks/useDeployListPage.ts
> +  offset: number
You may want to add default values here.

2023-04-03 08:47 UTC, PaulFarault commented on src/hooks/useDeployListPage.ts
> +export function useDeployListPage(
In my understanding, a restuful API with a lot of records is organised as "pages". Also, the "past" word is not useful as logs are always related to a past operation.

Hence you should rename `useFetchLogsPage` which returns a `logsPage` array using a `fetchLogsPage` function.

2023-04-03 08:47 UTC, PaulFarault commented on src/pages/deploy/index.tsx
> +        // <DeployLogs deployTab={pastDeploymentsRichList} />
You can simply remove this line if it's not in use anymore.

2023-04-03 08:57 UTC, jpsavy commented on src/components/Deploy/DeployLogs/DeployLogsPages.tsx
> +              'bg-gray-200 text-gray-700',
Done

2023-04-05 15:15 UTC, PaulFarault approved these changes

2023-04-06 08:39 UTC, merged