feat: main page content
TOSIT-IO/tdp-ui pull request #187
Opened 2023-02-28 10:23 UTC by pvalentin01

#### Which issue(s) this PR fixes

Fixes #108 

#### Additional comments

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-03-03 10:45 UTC, PaulFarault requested changes
You should at least remove the dark mode (as the background color will stay white) and try to center the buttons.

2023-03-06 17:10 UTC, jpsavy approved these changes
Nice main page content.

2023-03-08 09:50 UTC, jpsavy approved these changes
In dark mode the titles of the home page are now visible.

2023-03-08 14:12 UTC, PaulFarault requested changes
This is quite good for your first PR using React! Most of my comments are about refactoring (you shouldn't define components inside of other components).

2023-03-08 14:12 UTC, PaulFarault commented on src/pages/index.tsx
> +    ]
You could use this syntax instead:

```ts
  const pastDeploymentsRichList = pastDeploymentsRich?.slice(-1)
```

2023-03-08 14:12 UTC, PaulFarault commented on src/pages/index.tsx
> +  const m_services = useSelectServices().value.map((v) => ({
You should use camelCase to name your variables and functions

2023-03-08 14:12 UTC, PaulFarault commented on src/pages/index.tsx
> +  }
This could be in it's own `Status` or `Label` component.

2023-03-08 14:12 UTC, PaulFarault commented on src/pages/index.tsx
> +  }
This should be a distinct component (defined outside of `DashboardPage`)

2023-05-02 16:35 UTC, pvalentin01 commented on src/pages/index.tsx
> +  const pastDeployementBlock = (pastDeploymentsRichList) => {
Done

2023-05-02 16:35 UTC, pvalentin01 commented on src/pages/index.tsx
> +    ]
Done

2023-05-02 16:35 UTC, pvalentin01 commented on src/pages/index.tsx
> +  const m_services = useSelectServices().value.map((v) => ({
Done

2023-05-02 16:35 UTC, pvalentin01 commented on src/pages/index.tsx
> +  }
Done

2023-05-02 16:35 UTC, pvalentin01 commented on src/pages/index.tsx
> +  }
Done

2023-05-10 16:07 UTC, PaulFarault approved these changes
Good job Pierre!

I modified it so it can match with what Sergeï did in his last PR (#201).

We'll have to refactor the `Logs` components but it may be wise to wait for server update.

2023-05-11 09:25 UTC, sergkudinov commented
I sujest to modify the screen to the following:
<img width="1680" alt="image" src="https://github.com/TOSIT-IO/tdp-ui/assets/23199590/d03ec34b-392d-4d90-b80d-bd6c982eb37d">

2023-05-11 10:59 UTC, sergkudinov requested changes
Please, apply the changes

2023-05-11 10:59 UTC, sergkudinov commented on src/pages/index.tsx
> +const DashboardPage = () => {
Use a shorter version as above

2023-05-12 13:20 UTC, PaulFarault commented on src/components/Dashboard/ServicesSection.tsx
> +    data: services,
imo it improves readability. It's not a big increase for the benefit.

2023-05-12 15:02 UTC, pvalentin01 commented on src/components/Dashboard/ServicesSection.tsx
> +  Service as ServiceCard,
done

2023-05-12 15:02 UTC, pvalentin01 commented on src/components/Dashboard/ServicesSection.tsx
> +const ServiceCard = ({ service }: { service: ServiceCard }) => {
done

2023-05-12 15:02 UTC, pvalentin01 commented on src/components/Dashboard/DeploySection.tsx
> +export const DeploySection = () => {
done

2023-05-12 15:02 UTC, pvalentin01 commented on src/components/Dashboard/LogsSection.tsx
> +export const LogsSection = () => {
done

2023-05-12 15:03 UTC, pvalentin01 commented on src/pages/index.tsx
> +const DashboardPage = () => {
done

2023-05-12 15:08 UTC, pvalentin01 commented on src/components/Dashboard/ServicesSection.tsx
> +    data: services,
Nothing done, awaiting your reply

2023-05-15 09:51 UTC, sergkudinov commented on src/components/Dashboard/ServicesSection.tsx
> +}
We will refactor all `Loading...` components in the feature, we can decide later depending on how this component will look like. Ok for leaving as is for the moment.

2023-05-15 10:18 UTC, sergkudinov commented on src/components/Dashboard/ServicesSection.tsx
> +  if (isError) console.error('Error while fetching services', error)
You did remove `if (isLoading)` section. I didn't actually want to highlight it in the review comment. But indeed, it is not really necessary displaying here, because:
1. We use the same `useGetServicesApiV1ServiceGetQuery` in the sidebar, and `Loading...` is displayed globally on the first page render and using `LoadingServices` component. So, the value for dashboard's services is taken from cache.
2. It is not always justified to display loading preloader from the UX perspectives. To my mind this is the case here, we don't need.

Since you removed the `if (isLoading)` section, merge please `RunningServices` into `ServicesSection` to make just 1 component despite @PaulFarault comment above which is not a case anymore.

2023-05-15 10:19 UTC, sergkudinov commented on src/components/Dashboard/ServicesSection.tsx
> +}
However, see my comment below

2023-05-15 10:32 UTC, sergkudinov commented on src/components/Dashboard/ServicesSection.tsx
> +    data: services,
@PaulFarault so, to keep consistency, we should do it everywhere (like in `src/components/Logs/DeploymentsLogs.tsx`, `src/components/Logs/OperationsLogs.tsx`, etc...) everytime reflecting how to properly name it loosing time and giving long names.

This is similar what I did in my RTK refactor, I gave a name `Page` for all the components exporting pages (like in `src/pages/services/[serviceId].tsx`, `src/pages/deploy/index.tsx`, etc...) instead of inventing specific names for everyone. It saves time and imporves consistency. There is no need for custom names. Same for this case. I would only agree if we had to distinguish variables between multiple entities inside one component like [here](https://github.com/TOSIT-IO/tdp-ui/blob/master/src/pages/deploy/new/reconfigure.tsx#L9-L18).

@pvalentin01 you must also follow the code style and rename `DashboardPage` to jsut `Page` in `src/pages/index.tsx`.

2023-05-15 10:34 UTC, sergkudinov commented on src/pages/index.tsx
> +const DashboardPage = () => {
also, rename `DashboardPage` to `Page`, see my above comment

2023-05-15 10:36 UTC, sergkudinov commented
ok for new look of the page, see my above comments.

2023-05-15 12:41 UTC, sergkoudi requested changes
ok for the new look of the page, see my above comments.

2023-05-16 14:09 UTC, PaulFarault commented on src/components/Dashboard/ServicesSection.tsx
> +  if (isError) console.error('Error while fetching services', error)
Sure, if there are no loading and error sections there is no point to keep a distinct component.

We may want to open an issue about loading. It's not clear what `LoadingServices` is loading (and why) at first and what it is not.

2023-05-16 14:30 UTC, PaulFarault commented on src/components/Dashboard/ServicesSection.tsx
> +    data: services,
Agree, we must be consistent. Problem is that it's hard to read what the hooks are returning (for example `useGetComponentApiV1ServiceServiceIdComponentComponentIdGetQuery`). The easiest answer to that for now is to rename the `data` returned (OR we can plan something to improve hooks naming).

2023-05-16 14:36 UTC, sergkudinov commented on src/components/Dashboard/ServicesSection.tsx
> +    data: services,
We have already descussed about [this](https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/?h=operationid#using-the-path-operation-function-name-as-the-operationid). Let's plan it on the tdp-server side.

2023-05-17 12:21 UTC, pvalentin01 commented on src/pages/index.tsx
> +const DashboardPage = () => {
done

2023-05-17 12:28 UTC, pvalentin01 commented on src/components/Dashboard/ServicesSection.tsx
> +}
done, `DashboardPage` renamed to just `Page` in `src/pages/index.tsx`

2023-05-17 12:29 UTC, sergkudinov approved these changes
Ok for me

2023-05-17 12:32 UTC, merged