40 send service configuration to the server
TOSIT-IO/tdp-ui pull request #46
Opened 2022-11-17 13:13 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes #40 
Fixes #38 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-11-17 17:23 UTC, jpsavy approved these changes
No more Runtime Error
TypeError: prev is null
when changing the value in yarn service -> section capacity_scheduler -> key yarn.scheduler.capacity.resource-calculator

2022-11-18 07:47 UTC, gboutry commented
Getting a 400 status code should be handled correctly. There's currently a nextjs modal saying error 400.

```
Unhandled Runtime Error

AxiosError: Request failed with status code 400
Call Stack
```

Moreover, I thin we should have something telling us the validation was successful (or not). When I tried, and the validation was successful, nothing happened in the screen, the text input even stayed filled with the message. This is not very user friendly

2022-11-18 07:58 UTC, gboutry requested changes

2022-11-18 07:58 UTC, gboutry commented on src/app/services/ComponentMenu.tsx
> +  const menuItems = [{ id: 'commons', link: `/services/${serviceId}` }].concat(
I don't think `commons` is the right term for this.

The route `/services/${serviceId}` serves the service definition. It's just that the service definition is shared with the components.

2022-11-18 07:58 UTC, gboutry commented on src/components/VariablesDisplay/VariableField.tsx
> +      const newVariable = JSON.parse(event.target.value)
I don't think parsing the value from the text input is a good idea. We want to give good user experience, and with this, you're saying every text input needs to have double quotes or it will fail, which is not user friendly.

This behavior is error prone because user can't easy distinguish between the values `true` and `"true"` which have different meaning.

2022-11-18 07:58 UTC, gboutry commented on src/components/VariablesDisplay/VariableField.tsx
> +      const newVariable = JSON.parse(event.target.value)
Another thing, the values `yes` or `no` are considered boolean values in YAML but not in JSON, with this, they are handled as `"no"` and will be registered as string in the server, which will break things.

2022-11-18 08:37 UTC, PaulFarault commented on src/components/VariablesDisplay/VariableField.tsx
> +      const newVariable = JSON.parse(event.target.value)
I'm not sure to understand, `"true"` and `true` are currently distinguished. The text input is even turning red when writing a boolean with a typo or a string without quote.

2022-11-18 08:53 UTC, gboutry commented on src/components/VariablesDisplay/VariableField.tsx
> +      const newVariable = JSON.parse(event.target.value)
How does an user understand that `true` will be interpreted as a boolean, and `"true"` will be interpreted as string ? these are different semantics, and only relying on the double quotes is a mistake imho

2022-11-18 09:28 UTC, PaulFarault commented on src/components/VariablesDisplay/VariableField.tsx
> +      const newVariable = JSON.parse(event.target.value)
There are a lot of improvements to be made on the values UI:

- explode array entries,
- use a toogle button for booleans,
- do not put quotes for strings,
- use colors to distinguish types,
- handle jinja variables as tag,
- ...

I agree with you but, in my opinion, this minimal display is sufficient for this first PR (which is dedicated to sending variables to the server and not to displaying variables).

2022-11-18 09:29 UTC, PaulFarault commented on src/app/services/ComponentMenu.tsx
> +  const menuItems = [{ id: 'commons', link: `/services/${serviceId}` }].concat(
Then `shared`? Any other suggestion?

2022-11-18 14:03 UTC, PaulFarault commented
I added a small "OK" for 3 second on success.

> Getting a 400 status code should be handled correctly.

It would be nice to centralize all Axios responses and errors management in a middleware and a notification system. I'd prefer to solve it in a separate PR (I'll do it along with #14 ).

2022-11-18 14:23 UTC, jpsavy approved these changes
On validation of a modification, "OK" appears correctly for 3 seconds if successful to the right of the "Validate" button.

2022-11-18 15:29 UTC, gboutry commented on src/app/services/ComponentMenu.tsx
> +  const menuItems = [{ id: 'commons', link: `/services/${serviceId}` }].concat(
`service` might be a good fit

2022-11-18 15:37 UTC, PaulFarault commented on src/app/services/ComponentMenu.tsx
> +  const menuItems = [{ id: 'commons', link: `/services/${serviceId}` }].concat(
done ✅

2022-11-18 15:43 UTC, gboutry approved these changes

2022-11-18 15:48 UTC, merged