52 deploy page
TOSIT-IO/tdp-ui pull request #56
Opened 2022-11-21 14:39 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes #52 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-11-21 15:10 UTC, gboutry requested changes
Input targets should not be re-ordered on modification

`,,` multiple colons input are possible while they shouldn't

2022-11-22 17:49 UTC, gboutry commented
The input text is nearly invisible. If you don't know it's there, it's hard

2022-11-24 15:30 UTC, gboutry commented on src/app/deploy/InputField.tsx
> +        htmlFor="email"
De we need an email address to deploy tdp ?

2022-11-24 15:52 UTC, PaulFarault commented on src/app/deploy/InputField.tsx
> +        htmlFor="email"
Thx! It should be better now.

2022-11-24 15:58 UTC, gboutry commented on src/app/deploy/InputField.tsx
> +        htmlFor="email"
the properti htmlFor still has the value `htmlFor`, which is wrong

2022-11-24 16:03 UTC, jpsavy approved these changes
A zookeeper_config has been successfully deployed.

2022-11-25 15:03 UTC, gboutry approved these changes

2022-11-25 15:08 UTC, merged