49 variables displayed as components
TOSIT-IO/tdp-ui pull request #57
Opened 2022-11-23 18:08 UTC by jpsavy

#### Which issue(s) this PR fixes

Fixes #49 

#### Additional comments

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-11-23 20:38 UTC, gboutry commented
Is it possible to have every inputs on the right aligned ? It would be cleaner in my opinion

2022-11-24 09:33 UTC, PaulFarault commented
Good job!

Would be nice to have a [button group](https://tailwindui.com/components/application-ui/elements/button-groups#component-dc2468c1992adb5950f2d93cf589a65e) which trigger `raw` or `view` views. @gboutry suggestion could then go on the `view` with the content of your PR.

Don't hesitate if you have better naming than `view`/`raw` (maybe icons).

2022-11-29 14:59 UTC, PaulFarault requested changes

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/index.tsx
> +  function RawViewButton() {
You should refactor this component into it's own file.

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/index.tsx
> +          <label className="invisible">T T</label>
What is this label?

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/index.tsx
> +        <span className="isolate inline-flex rounded-md shadow-sm">
You shouldn't use both `span` and `div` if they both wrap the whole component.

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/index.tsx
> +          <RawViewButton />
You may not want to put the `<RawViewButton />` inside the "validate" group. Putting it under this `div` seems more logical as we're probably going to refactore these 2 parts sparately later.

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/VariablesList.tsx
> +            <VariableFieldRaw key={k} prop={k} value={v} parent={parent} />
Why not using the `isRaw` condition right here instead of the whole block? It'll allow you to have the same column style for both _raw_ and _view_ toggles.

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/VariableField.tsx
> +  function ArrayList() {
You should refactor all components in their own file!

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/VariableField.tsx
> +          ? ArrayList()
It'll may make more sense to use components instead of functions here.

2022-11-29 14:59 UTC, PaulFarault commented on src/components/VariablesDisplay/VariableField.tsx
> +      </div>
Would it be possible to check the `isRaw` condition here and add a `<Raw />` component instead of having 2 whole `<VariableFieldXxx />` components?

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/index.tsx
> +  function RawViewButton() {
Done

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/index.tsx
> +          <label className="invisible">T T</label>
Done

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/index.tsx
> +        <span className="isolate inline-flex rounded-md shadow-sm">
Done

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/index.tsx
> +          <RawViewButton />
Done

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/VariablesList.tsx
> +            <VariableFieldRaw key={k} prop={k} value={v} parent={parent} />
Done

2022-12-05 10:49 UTC, jpsavy commented on src/components/VariablesDisplay/VariableField.tsx
> +  function ArrayList() {
Done

2022-12-05 10:50 UTC, jpsavy commented on src/components/VariablesDisplay/VariableField.tsx
> +          ? ArrayList()
Done

2022-12-05 10:50 UTC, jpsavy commented on src/components/VariablesDisplay/VariableField.tsx
> +      </div>
Done

2022-12-06 08:33 UTC, gboutry reviewed
While testing this PR, I have a lot of error messages in the console about duplicated keys in the objects holding the configuration.

I tested against master branch, and there's no error.

Can you look into it ?

```
Warning: Encountered two children with the same key, `cluster_name`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
div
VariableField@webpack-internal:///./src/components/VariablesDisplay/VariablesList/VariableField/index.tsx:17:46
VariablesList@webpack-internal:///./src/components/VariablesDisplay/VariablesList/index.tsx:11:43
div
form
VariablesContextProvider@webpack-internal:///./src/components/VariablesDisplay/contexts/VariablesContext.tsx:16:43
VariablesDisplay@webpack-internal:///./src/components/VariablesDisplay/index.tsx:21:67
ServicePage@webpack-internal:///./src/pages/services/[serviceId].tsx:19:74
div
ServiceLayout@webpack-internal:///./src/app/services/layout.tsx:17:25
main
div
DashboardLayout@webpack-internal:///./src/app/dashboard/layout.tsx:11:25
TdpClientContextProvider@webpack-internal:///./src/contexts/TdpClientContext.tsx:21:25
LoginPortal@webpack-internal:///./src/app/LoginPortal.tsx:13:25
AuthProvider@webpack-internal:///./node_modules/react-oidc-context/dist/esm/react-oidc-context.js:123:7
AuthContextProvider@webpack-internal:///./src/contexts/AuthContextProvider.tsx:19:25
MyApp@webpack-internal:///./src/pages/_app.tsx:14:38
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3209
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6087
Container@webpack-internal:///./node_modules/next/dist/client/index.js:57:1
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:170:25
Root@webpack-internal:///./node_modules/next/dist/client/index.js:337:37 next-dev.js:20:25
```

2022-12-06 14:52 UTC, jpsavy commented
@gboutry  https://github.com/TOSIT-IO/tdp-ui/pull/57#pullrequestreview-1206111493
Done

2022-12-06 16:01 UTC, PaulFarault approved these changes

2022-12-07 11:26 UTC, gboutry approved these changes

2022-12-07 14:24 UTC, merged