74 run page
TOSIT-IO/tdp-ui pull request #78
Opened 2022-12-09 08:52 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes #74 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-12-09 09:54 UTC, gboutry requested changes
- Deploy From Sources should not be able to complete with an empty list of operations (it is translated into deploy targets all on the server)
- Deploy From Targets should not be able to complete with an empty list of operations (it is translated into deploy targets all on the server)
- Run should not be able to complete with an empty list of operations (the server returns an error)
- Since input field values are kept even when changing deploy mode, there should be a button to clear inputs / reset to defaults
- In Custom mode, clicking outside of the field does not validate the input, and clicking on deploy will failed stating that there is no operation.

2022-12-09 10:20 UTC, PaulFarault commented
@gboutry 

> Deploy From Sources should not be able to complete with an empty list of operations (it is translated into deploy targets all on the server)
> Deploy From Targets should not be able to complete with an empty list of operations (it is translated into deploy targets all on the server)
> Run should not be able to complete with an empty list of operations (the server returns an error)

I asked myself the question for deploy from sources/targets and thought that it was a bit dumb but not incorrect as it will trigger the deploy all. Do you want me to put a condition on those fields?

> Since input field values are kept even when changing deploy mode, there should be a button to clear inputs / reset to defaults

In your opinion, what is the best option:

- Empty the fields when changing deploy mode (between `sources` and `targets`, as `custom` won't share the same operations)
- Add a clear button on the configuration step
- Merge the `sources` and `targets` options on the 1st step, and add a toggle for it on the 2nd step

> In Custom mode, clicking outside of the field does not validate the input, and clicking on deploy will failed stating that there is no operation.

Right, the `onClickOutside`only apply when modifying an operation, not on the main input. I'll add it there and also add a check if empty condition.

2022-12-09 10:22 UTC, gboutry commented on src/components/Deploy/2-ConfigurationStep/Fields/OperationsField/OperationField.tsx
> +  const isFieldDisabled = deployMethod === DeployMethodsEnum.ALL
```suggestion
  const isFieldDisabled = deployMethod === DeployMethodsEnum.ALL
```

I don't understand the purpose of isFieldDisabled since you're not showing it in all deployment ?

2022-12-09 10:22 UTC, gboutry commented on src/pages/deploy.tsx
> +      </div> */}
```suggestion
```

Is that still needed ?

2022-12-09 10:22 UTC, gboutry commented on src/components/Deploy/2-ConfigurationStep/ConfigurationStep.tsx
> +          <span>Preview</span>
```suggestion
          <span>Review</span>
```

Why is the button name Preview while it's for the Review page ?

2022-12-09 10:22 UTC, gboutry commented on src/contexts/DeployContext.tsx
> +    res?.data?.state && toast.info(`Deploy status: ${res.data.state}`)
```suggestion
    res?.data?.state && toast.info(`Deploy status: ${res.data.id}`)
```

I think it would be more interesting to display the id instead of the state, since the state will always be pending

2022-12-09 10:24 UTC, PaulFarault commented on src/components/Deploy/2-ConfigurationStep/ConfigurationStep.tsx
> +          <span>Preview</span>
I'm hesitating between `Review` and `Preview`, what do you think will fit best?

2022-12-09 10:26 UTC, PaulFarault commented on src/components/Deploy/2-ConfigurationStep/Fields/OperationsField/OperationField.tsx
> +  const isFieldDisabled = deployMethod === DeployMethodsEnum.ALL
```suggestion
```

You're right, it is not used anymore.

2022-12-09 10:27 UTC, gboutry commented
> I asked myself the question for deploy from sources/targets and thought that it was a bit dumb but not incorrect as it will trigger the deploy all. Do you want me to put a condition on those fields?

In the case of target it's okay because it's semantically the same, but in the case of sources, the behavior might not be the one expected,


> Since input field values are kept even when changing deploy mode, there should be a button to clear inputs / reset to defaults
> 
> In your opinion, what is the best option:
> 
>     * Empty the fields when changing deploy mode (between `sources` and `targets`, as `custom` won't share the same operations)
> 
>     * Add a clear button on the configuration step
> 
>     * Merge the `sources` and `targets` options on the 1st step, and add a toggle for it on the 2nd step

I think having a
- First type: Deploy all, no options, easy
- Second type: Deploy Advanced: you can choose sources, targets... you can have empty operation lists 
- Third type: Deploy operations: you can only choose operations

2022-12-09 10:29 UTC, PaulFarault commented
> First type: Deploy all, no options, easy

No restart or filter on this one?

2022-12-09 10:30 UTC, gboutry commented
> > First type: Deploy, no options, easy
> 
> No restart or filter on this one?

No options, just deploy

2022-12-09 10:42 UTC, gboutry commented on src/components/Deploy/2-ConfigurationStep/ConfigurationStep.tsx
> +          <span>Preview</span>
If you can modify what will happen on the page, it's a Review, if you cannot, it's a Preview

2022-12-09 14:29 UTC, gboutry commented on src/contexts/DeployContext.tsx
> +    res?.data?.state && toast.info(`Deploy status: ${res.data.id}`)
```suggestion
    res?.data?.state && toast.info(`Deployment: ${res.data.id}`)
```

Status does not make sense

2022-12-09 15:05 UTC, PaulFarault commented on src/components/Deploy/2-ConfigurationStep/Fields/OperationsField/OperationField.tsx
> +  const isFieldDisabled = deployMethod === DeployMethodsEnum.ALL
Hum, I'll keep it to refactor the step. Maybe I'll merge the ones that are using the DAG.

2022-12-09 16:45 UTC, PaulFarault commented
I made it simple and created #87 and #88. What do you think about it now @gboutry?

2022-12-12 10:11 UTC, gboutry requested changes

2022-12-12 10:11 UTC, gboutry commented on src/components/Deploy/3-ReviewStep/ReviewStep.tsx
> +//TODO: Allow to review the configuration before deploying
Can you add // TODO: # issue number - description ?

2022-12-12 10:44 UTC, PaulFarault commented on src/components/Deploy/3-ReviewStep/ReviewStep.tsx
> +//TODO: Allow to review the configuration before deploying
```suggestion
//TODO: #73 Preview operations execution plan before deploy
```

2022-12-13 11:57 UTC, PaulFarault commented on src/components/Deploy/2-ConfigurationStep/ConfigurationStep.tsx
> +          disabled={!operations.length}
done

2022-12-13 15:04 UTC, gboutry requested changes
Custom deployments send a DeployRequest and not an OperationsRequest

2022-12-13 15:04 UTC, gboutry commented on src/clients/axiosClient.tsx
> +      console.error(err)
```suggestion

```

2022-12-13 15:52 UTC, gboutry requested changes
Deploying with targets performs an OperationsRequest instead of a DeployRequest

2022-12-13 18:47 UTC, gboutry approved these changes

2022-12-13 20:56 UTC, merged