85 layout refactoring
TOSIT-IO/tdp-ui pull request #95
Opened 2022-12-15 16:44 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes #85 

#### Additional comments

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-12-18 14:48 UTC, gboutry requested changes

2022-12-18 14:48 UTC, gboutry commented on .prettierignore
> +/docker
```suggestion
/docker

```
missing new linea

2022-12-18 14:48 UTC, gboutry commented on src/app/dashboard/layout.tsx
> +                src="/TDP_LOGO_INVERSE_notext.png"
Are you using git lfs to store the image, or directly storing in the repo ?

2022-12-18 14:48 UTC, gboutry commented on src/hooks/useDeployLogInfos.ts
> +export function useDeployLogInfos(deployLogId: number) {
This doesn't look like it's used in the project, why are you adding this in `layout-refactoring' ?

2022-12-18 21:13 UTC, PaulFarault commented on src/app/dashboard/layout.tsx
> +                src="/TDP_LOGO_INVERSE_notext.png"
No, it doesn't seem to work with this repo:

```
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

2022-12-19 00:13 UTC, gboutry requested changes
Static export does not work, I had to add `next.config.js`:

```js
const nextConfig = {
    images: {
        unoptimized: true
    }
}

module.exports  = nextConfig;
```

2022-12-19 00:34 UTC, gboutry approved these changes

2022-12-19 00:35 UTC, merged